name: Secret scan

on:
  push:
    branches: [master]
  pull_request:

jobs:
  trufflehog:
    uses: DoubtfulTurnip/.github/.github/workflows/trufflehog-scan.yml@main
    permissions:
      contents: read
